// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		ElAside: typeof import('element-plus/es')['ElAside']
		ElAvatar: typeof import('element-plus/es')['ElAvatar']
		ElBadge: typeof import('element-plus/es')['ElBadge']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElContainer: typeof import('element-plus/es')['ElContainer']
		ElDropdown: typeof import('element-plus/es')['ElDropdown']
		ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
		ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
		ElEmpty: typeof import('element-plus/es')['ElEmpty']
		ElFooter: typeof import('element-plus/es')['ElFooter']
		ElForm: typeof import('element-plus/es')['ElForm']
		ElFormItem: typeof import('element-plus/es')['ElFormItem']
		ElHeader: typeof import('element-plus/es')['ElHeader']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElImage: typeof import('element-plus/es')['ElImage']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElMain: typeof import('element-plus/es')['ElMain']
		ElMenu: typeof import('element-plus/es')['ElMenu']
		ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
		ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
		ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
		ElSwitch: typeof import('element-plus/es')['ElSwitch']
		ElTable: typeof import('element-plus/es')['ElTable']
		ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
		ElTag: typeof import('element-plus/es')['ElTag']
		HjButton: typeof import('./src/components/button/src/hj-button.vue')['default']
		HjHeader: typeof import('./src/components/header/src/hj-header.vue')['default']
		HjMenu: typeof import('./src/components/menu/src/hj-menu.vue')['default']
		HjMenuItem: typeof import('./src/components/menu/src/hj-menu-item.vue')['default']
		Icon: typeof import('./src/components/icon/src/icon.vue')['default']
		IconButton: typeof import('./src/components/button/src/icon-button.vue')['default']
		IconEpEdit: typeof import('~icons/ep/edit')['default']
		IconEpItem: typeof import('~icons/ep/item')['default']
		IEpEdit: typeof import('~icons/ep/edit')['default']
		Menu: typeof import('./src/components/hj-menu/src/menu.vue')['default']
		MenuItem: typeof import('./src/components/menu/src/menu-item.vue')['default']
		PageContent: typeof import('./src/components/page-content/src/page-content.vue')['default']
		PersonItem: typeof import('./src/components/person/src/person-item.vue')['default']
		PersonList: typeof import('./src/components/person/src/person-list.vue')['default']
		PersonPanel: typeof import('./src/components/person/src/person-panel.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		Src: typeof import('./src/components/page-content/src/index.vue')['default']
		SunnyIcon: typeof import('./src/components/icon/src/Sunny-icon.vue')['default']
	}
}
