// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		ElAside: typeof import('element-plus/es')['ElAside']
		ElContainer: typeof import('element-plus/es')['ElContainer']
		ElFooter: typeof import('element-plus/es')['ElFooter']
		ElHeader: typeof import('element-plus/es')['ElHeader']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElMain: typeof import('element-plus/es')['ElMain']
		Icon: typeof import('./src/components/icon/src/icon.vue')['default']
		IconEpEdit: typeof import('~icons/ep/edit')['default']
		IconEpItem: typeof import('~icons/ep/item')['default']
		IEpEdit: typeof import('~icons/ep/edit')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
	}
}
